title:            pdv.so
description:      Probably quite boring.
url:              https://pdv.so
signoff:          Oreckz
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          https://pdv.so/general/2015/03/08/who-am-i/
  - name:         Twitter
    url:          https://www.twitter.com/oreckstatler
    external:     true
  - name:         Email
    url:          mailto:oreckstatler@gmail.com
    external:     true
  - name:         GitHub
    url:          https://github.com/oreckz
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
